In [2]:
import numpy as np
import pandas as pd

In [9]:
#uzeto iz fajla za analizu podataka
kolone = ["ID", "Age", "Gender", "Education", "Country", "Ethnicity", 
            "Nscore", "Escore", "Oscore", "Ascore", "Cscore", "Impulsiveness", "SS", 
            "Alchocol", "Amphet", "Amyl", "Benzos", "Caff", "Canabis", "Choc", "Coke", "Crack", "Ecstasy", 
            "Heroin", "Ketamin", "LegalH", "LSD", "Meth", "Mushrooms", "Nicotine", "Semer", "VSA"]

podaci = pd.read_csv('drug_consumption.data', names = kolone)

podaci = podaci.drop('ID', axis = 1)
podaci

,Age,Gender,Education,Country,Ethnicity,Nscore,Escore,Oscore,Ascore,Cscore,...,Ecstasy,Heroin,Ketamin,LegalH,LSD,Meth,Mushrooms,Nicotine,Semer,VSA
0,0.49788,0.48246,-0.05921,0.96082,0.12600,0.31287,-0.57545,-0.58331,-0.91699,-0.00665,...,CL0,CL0,CL0,CL0,CL0,CL0,CL0,CL2,CL0,CL0
1,-0.07854,-0.48246,1.98437,0.96082,-0.31685,-0.67825,1.93886,1.43533,0.76096,-0.14277,...,CL4,CL0,CL2,CL0,CL2,CL3,CL0,CL4,CL0,CL0
2,0.49788,-0.48246,-0.05921,0.96082,-0.31685,-0.46725,0.80523,-0.84732,-1.62090,-1.01450,...,CL0,CL0,CL0,CL0,CL0,CL0,CL1,CL0,CL0,CL0
3,-0.95197,0.48246,1.16365,0.96082,-0.31685,-0.14882,-0.80615,-0.01928,0.59042,0.58489,...,CL0,CL0,CL2,CL0,CL0,CL0,CL0,CL2,CL0,CL0
4,0.49788,0.48246,1.98437,0.96082,-0.31685,0.73545,-1.63340,-0.45174,-0.30172,1.30612,...,CL1,CL0,CL0,CL1,CL0,CL0,CL2,CL2,CL0,CL0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1880,-0.95197,0.48246,-0.61113,-0.57009,-0.31685,-1.19430,1.74091,1.88511,0.76096,-1.13788,...,CL0,CL0,CL0,CL3,CL3,CL0,CL0,CL0,CL0,CL5
1881,-0.95197,-0.48246,-0.61113,-0.57009,-0.31685,-0.24649,1.74091,0.58331,0.76096,-1.51840,...,CL2,CL0,CL0,CL3,CL5,CL4,CL4,CL5,CL0,CL0
1882,-0.07854,0.48246,0.45468,-0.57009,-0.31685,1.13281,-1.37639,-1.27553,-1.77200,-1.38502,...,CL4,CL0,CL2,CL0,CL2,CL0,CL2,CL6,CL0,CL0
1883,-0.95197,0.48246,-0.61113,-0.57009,-0.31685,0.91093,-1.92173,0.29338,-1.62090,-2.57309,...,CL3,CL0,CL0,CL3,CL3,CL0,CL3,CL4,CL0,CL0
1884,-0.95197,-0.48246,-0.61113,0.21128,-0.31685,-0.46725,2.12700,1.65653,1.11406,0.41594,...,CL3,CL0,CL0,CL3,CL3,CL0,CL3,CL6,CL0,CL2

In [15]:
klase = []
atributi = []
for x in podaci.columns:
    if x == 'Alchocol':
        break
    atributi.append(x)
print(atributi)

for x in podaci.columns:
    if x not in atributi:
        klase.append(x)
print(klase)

['Age', 'Gender', 'Education', 'Country', 'Ethnicity', 'Nscore', 'Escore', 'Oscore', 'Ascore', 'Cscore', 'Impulsiveness', 'SS']
['Alchocol', 'Amphet', 'Amyl', 'Benzos', 'Caff', 'Canabis', 'Choc', 'Coke', 'Crack', 'Ecstasy', 'Heroin', 'Ketamin', 'LegalH', 'LSD', 'Meth', 'Mushrooms', 'Nicotine', 'Semer', 'VSA']

In [38]:
#podesavanje podataka malo
for x in klase:
    a = podaci[x].unique()
    a.sort()
    print(a)

['CL0' 'CL1' 'CL2' 'CL3' 'CL4' 'CL5' 'CL6']
['CL0' 'CL1' 'CL2' 'CL3' 'CL4' 'CL5' 'CL6']
['CL0' 'CL1' 'CL2' 'CL3' 'CL4' 'CL5' 'CL6']
['CL0' 'CL1' 'CL2' 'CL3' 'CL4' 'CL5' 'CL6']
['CL0' 'CL1' 'CL2' 'CL3' 'CL4' 'CL5' 'CL6']
['CL0' 'CL1' 'CL2' 'CL3' 'CL4' 'CL5' 'CL6']
['CL0' 'CL1' 'CL2' 'CL3' 'CL4' 'CL5' 'CL6']
['CL0' 'CL1' 'CL2' 'CL3' 'CL4' 'CL5' 'CL6']
['CL0' 'CL1' 'CL2' 'CL3' 'CL4' 'CL5' 'CL6']
['CL0' 'CL1' 'CL2' 'CL3' 'CL4' 'CL5' 'CL6']
['CL0' 'CL1' 'CL2' 'CL3' 'CL4' 'CL5' 'CL6']
['CL0' 'CL1' 'CL2' 'CL3' 'CL4' 'CL5' 'CL6']
['CL0' 'CL1' 'CL2' 'CL3' 'CL4' 'CL5' 'CL6']
['CL0' 'CL1' 'CL2' 'CL3' 'CL4' 'CL5' 'CL6']
['CL0' 'CL1' 'CL2' 'CL3' 'CL4' 'CL5' 'CL6']
['CL0' 'CL1' 'CL2' 'CL3' 'CL4' 'CL5' 'CL6']
['CL0' 'CL1' 'CL2' 'CL3' 'CL4' 'CL5' 'CL6']
['CL0' 'CL1' 'CL2' 'CL3' 'CL4']
['CL0' 'CL1' 'CL2' 'CL3' 'CL4' 'CL5' 'CL6']

In [138]:
podaci_skalirano = podaci.copy()

opisni_niz1 = podaci['Alchocol'].unique()
opisni_niz1.sort()
opisni_niz2 = podaci['Semer'].unique()
opisni_niz2.sort()

niz1 = [0, 1, 2, 3, 4, 5, 6]
niz2 = [0, 1, 2, 3, 4]

def opisi_podatke(atribut, niz, opisni_niz):
    n = len(niz)
    mapa_podataka = {}
    for i in range(n):
        mapa_podataka.update({niz[i]: opisni_niz[i]})
#         print(f'{niz[i]}:{opisni_niz[i]}', end = ' ')
    print(mapa_podataka)
    podaci_skalirano[atribut] = podaci_opisno[atribut].map(mapa_podataka)
    
podaci_skalirano['Ketamin'] = podaci_skalirano['Ketamin'].astype('category')
print(podaci_skalirano['Ketamin'])

podaci_skalirano
podaci_skalirano['Ketamin'][0] = 0
print(podaci_skalirani['Ketamin'][0])
#opisi_podatke(x, opisni_niz1, niz1)
podaci_skalirano

0       CL0
1       CL2
2       CL0
3       CL2
4       CL0
       ...
1880    CL0
1881    CL0
1882    CL2
1883    CL0
1884    CL0
Name: Ketamin, Length: 1885, dtype: category
Categories (7, object): ['CL0', 'CL1', 'CL2', 'CL3', 'CL4', 'CL5', 'CL6']

TypeError: Cannot setitem on a Categorical with a new category (0), set the categories first

In [119]:
mapa = {'Ecstasy': {'C0': 0, 'C1': 1, 'C2': 2, 'C3': 3, 'C4': 4, 'C5': 5, 'C6': 6}}
podaci_skalirano = podaci_skalirano.replace(mapa)
podaci_skalirano

,Age,Gender,Education,Country,Ethnicity,Nscore,Escore,Oscore,Ascore,Cscore,...,Ecstasy,Heroin,Ketamin,LegalH,LSD,Meth,Mushrooms,Nicotine,Semer,VSA
0,0.49788,0.48246,-0.05921,0.96082,0.12600,0.31287,-0.57545,-0.58331,-0.91699,-0.00665,...,CL0,CL0,CL0,CL0,CL0,CL0,CL0,CL2,CL0,CL0
1,-0.07854,-0.48246,1.98437,0.96082,-0.31685,-0.67825,1.93886,1.43533,0.76096,-0.14277,...,CL4,CL0,CL2,CL0,CL2,CL3,CL0,CL4,CL0,CL0
2,0.49788,-0.48246,-0.05921,0.96082,-0.31685,-0.46725,0.80523,-0.84732,-1.62090,-1.01450,...,CL0,CL0,CL0,CL0,CL0,CL0,CL1,CL0,CL0,CL0
3,-0.95197,0.48246,1.16365,0.96082,-0.31685,-0.14882,-0.80615,-0.01928,0.59042,0.58489,...,CL0,CL0,CL2,CL0,CL0,CL0,CL0,CL2,CL0,CL0
4,0.49788,0.48246,1.98437,0.96082,-0.31685,0.73545,-1.63340,-0.45174,-0.30172,1.30612,...,CL1,CL0,CL0,CL1,CL0,CL0,CL2,CL2,CL0,CL0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1880,-0.95197,0.48246,-0.61113,-0.57009,-0.31685,-1.19430,1.74091,1.88511,0.76096,-1.13788,...,CL0,CL0,CL0,CL3,CL3,CL0,CL0,CL0,CL0,CL5
1881,-0.95197,-0.48246,-0.61113,-0.57009,-0.31685,-0.24649,1.74091,0.58331,0.76096,-1.51840,...,CL2,CL0,CL0,CL3,CL5,CL4,CL4,CL5,CL0,CL0
1882,-0.07854,0.48246,0.45468,-0.57009,-0.31685,1.13281,-1.37639,-1.27553,-1.77200,-1.38502,...,CL4,CL0,CL2,CL0,CL2,CL0,CL2,CL6,CL0,CL0
1883,-0.95197,0.48246,-0.61113,-0.57009,-0.31685,0.91093,-1.92173,0.29338,-1.62090,-2.57309,...,CL3,CL0,CL0,CL3,CL3,CL0,CL3,CL4,CL0,CL0
1884,-0.95197,-0.48246,-0.61113,0.21128,-0.31685,-0.46725,2.12700,1.65653,1.11406,0.41594,...,CL3,CL0,CL0,CL3,CL3,CL0,CL3,CL6,CL0,CL2

In [120]:
podaci_skalirano.dtypes

Age              float64
Gender           float64
Education        float64
Country          float64
Ethnicity        float64
Nscore           float64
Escore           float64
Oscore           float64
Ascore           float64
Cscore           float64
Impulsiveness    float64
SS               float64
Alchocol          object
Amphet            object
Amyl              object
Benzos            object
Caff              object
Canabis           object
Choc              object
Coke              object
Crack             object
Ecstasy           object
Heroin            object
Ketamin           object
LegalH            object
LSD               object
Meth              object
Mushrooms         object
Nicotine          object
Semer             object
VSA               object
dtype: object

In [98]:
print(podaci_skalirano['Heroin'].unique())
podaci_skalirano['Age'].unique()

['CL0' 'CL1' 'CL2' 'CL3' 'CL5' 'CL6' 'CL4']

array([ 0.49788, -0.07854, -0.95197,  2.59171,  1.09449,  1.82213])